### ISSUE TITLE
CSYMPY_ASSERT() failure

### ISSUE THREAD

**Issue by certik** [sympy/csympy#370]
I just discovered a major bug (the latest master, 2793ba5abedfd04c9573ad37da30f4aa02ff77f7):
```
In [1]: from csympy import *

In [2]: var("x y z")
Out[2]: (x, y, z)

In [3]: e = (x+y+sqrt(3)*z+1)**15

In [4]: f = e*(e+1)

In [5]: g = f.expand()
python2.7: /home/ondrej/repos/csympy/src/mul.cpp:16: CSymPy::Mul::Mul(const CSymPy::RCP<const CSymPy::Number>&, CSymPy::map_basic_basic&&): Assertion `is_canonical(coef, dict_)' failed.

Abort caught. Printing stacktrace:

Traceback (most recent call last):
  File unknown, in _start()
  File "/build/buildd/eglibc-2.19/csu/libc-start.c", line 287, in __libc_start_main()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Modules/main.c", line 640, in Py_Main()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/pythonrun.c", line 955, in PyRun_SimpleFileExFlags()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/pythonrun.c", line 1377, in run_mod()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 673, in PyEval_EvalCode()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4346, in ext_do_call()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Objects/abstract.c", line 2529, in PyObject_Call()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Objects/funcobject.c", line 526, in function_call()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4730, in exec_statement()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 673, in PyEval_EvalCode()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4017, in call_function()
  File "/home/ondrej/repos/csympy/csympy/lib/csympy_wrapper.cpp", line 5803, in __pyx_pw_6csympy_3lib_14csympy_wrapper_5Basic_27expand()
    __pyx_r = __pyx_pf_6csympy_3lib_14csympy_wrapper_5Basic_26expand(((struct __pyx_obj_6csympy_3lib_14csympy_wrapper_Basic *)__pyx_v_self));
  File "/home/ondrej/repos/csympy/csympy/lib/csympy_wrapper.cpp", line 5839, in __pyx_pf_6csympy_3lib_14csympy_wrapper_5Basic_26expand()
    __pyx_t_1 = CSymPy::expand(((CSymPy::RCP<CSymPy::Basic const > &)__pyx_v_self->thisptr));
  File "/home/ondrej/repos/csympy/src/basic.cpp", line 40, in CSymPy::expand(CSymPy::RCP<CSymPy::Basic const> const&)
    if (is_a<Mul>(*self)) return mul_expand(rcp_static_cast<const Mul>(self));
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 493, in CSymPy::mul_expand(CSymPy::RCP<CSymPy::Mul const> const&)
    a = expand(a);
  File "/home/ondrej/repos/csympy/src/basic.cpp", line 41, in CSymPy::expand(CSymPy::RCP<CSymPy::Basic const> const&)
    if (is_a<Pow>(*self)) return pow_expand(rcp_static_cast<const Pow>(self));
  File "/home/ondrej/repos/csympy/src/pow.cpp", line 412, in CSymPy::pow_expand(CSymPy::RCP<CSymPy::Pow const> const&)
    RCP<const Basic> term = Mul::from_dict(overall_coeff, std::move(d));
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 214, in CSymPy::Mul::from_dict(CSymPy::RCP<CSymPy::Number const> const&, std::map<CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCPBasicKeyLess, std::allocator<std::pair<CSymPy::RCP<CSymPy::Basic const> const, CSymPy::RCP<CSymPy::Basic const> > > >&&)
    return rcp(new Mul(coef, std::move(d)));
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 16, in CSymPy::Mul::Mul(CSymPy::RCP<CSymPy::Number const> const&, std::map<CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCPBasicKeyLess, std::allocator<std::pair<CSymPy::RCP<CSymPy::Basic const> const, CSymPy::RCP<CSymPy::Basic const> > > >&&)
    CSYMPY_ASSERT(is_canonical(coef, dict_))
  File "/build/buildd/eglibc-2.19/assert/assert.c", line 101, in __GI___assert_fail()
  File "/build/buildd/eglibc-2.19/assert/assert.c", line 92, in __assert_fail_base()
  File "/build/buildd/eglibc-2.19/stdlib/abort.c", line 89, in __GI_abort()
  File "/build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c", line 56, in __GI_raise()
  File unknown, in killpg()
  File "/home/ondrej/repos/csympy/src/teuchos/Teuchos_stacktrace.cpp", line 449, in loc_abort_callback_print_stack()
    Teuchos::show_stacktrace();

Done.
Aborted (core dumped)
```

**Comment by certik** [comment]
This might be a related problem (in any case, it needs a separate test):
```
var("x y z")
e = (sqrt(3)*z+1)**2
f = e*(e+1)
g = f.expand()
```
gives
```
python2.7: /home/ondrej/repos/csympy/src/csympy_rcp.h:92: T* CSymPy::RCP<T>::operator->() const [with T = const CSymPy::Number]: Assertion `ptr_ != nullptr' failed.

Abort caught. Printing stacktrace:

Traceback (most recent call last):
  File unknown, in _start()
  File "/build/buildd/eglibc-2.19/csu/libc-start.c", line 287, in __libc_start_main()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Modules/main.c", line 640, in Py_Main()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/pythonrun.c", line 955, in PyRun_SimpleFileExFlags()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/pythonrun.c", line 1377, in run_mod()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 673, in PyEval_EvalCode()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4017, in call_function()
  File "/home/ondrej/repos/csympy/csympy/lib/csympy_wrapper.cpp", line 5803, in __pyx_pw_6csympy_3lib_14csympy_wrapper_5Basic_27expand()
    __pyx_r = __pyx_pf_6csympy_3lib_14csympy_wrapper_5Basic_26expand(((struct __pyx_obj_6csympy_3lib_14csympy_wrapper_Basic *)__pyx_v_self));
  File "/home/ondrej/repos/csympy/csympy/lib/csympy_wrapper.cpp", line 5839, in __pyx_pf_6csympy_3lib_14csympy_wrapper_5Basic_26expand()
    __pyx_t_1 = CSymPy::expand(((CSymPy::RCP<CSymPy::Basic const > &)__pyx_v_self->thisptr));
  File "/home/ondrej/repos/csympy/src/basic.cpp", line 40, in CSymPy::expand(CSymPy::RCP<CSymPy::Basic const> const&)
    if (is_a<Mul>(*self)) return mul_expand(rcp_static_cast<const Mul>(self));
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 495, in CSymPy::mul_expand(CSymPy::RCP<CSymPy::Mul const> const&)
    return mul_expand_two(a, b);
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 424, in CSymPy::mul_expand_two(CSymPy::RCP<CSymPy::Basic const> const&, CSymPy::RCP<CSymPy::Basic const> const&)
    rcp_static_cast<const Mul>(term)->coef_);
  File "/home/ondrej/repos/csympy/src/number.h", line 83, in CSymPy::imulnum(CSymPy::Ptr<CSymPy::RCP<CSymPy::Number const> > const&, CSymPy::RCP<CSymPy::Number const> const&)
    *self = mulnum(*self, other);
  File "/home/ondrej/repos/csympy/src/number.h", line 59, in CSymPy::mulnum(CSymPy::RCP<CSymPy::Number const> const&, CSymPy::RCP<CSymPy::Number const> const&)
    return self->mul(*other);
  File "/home/ondrej/repos/csympy/src/csympy_rcp.h", line 92, in CSymPy::RCP<CSymPy::Number const>::operator->() const
    CSYMPY_ASSERT(ptr_ != nullptr)
  File "/build/buildd/eglibc-2.19/assert/assert.c", line 101, in __GI___assert_fail()
  File "/build/buildd/eglibc-2.19/assert/assert.c", line 92, in __assert_fail_base()
  File "/build/buildd/eglibc-2.19/stdlib/abort.c", line 89, in __GI_abort()
  File "/build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c", line 56, in __GI_raise()
  File unknown, in killpg()
  File "/home/ondrej/repos/csympy/src/teuchos/Teuchos_stacktrace.cpp", line 449, in loc_abort_callback_print_stack()
    Teuchos::show_stacktrace();

Done.

Command terminated
```

**Comment by certik** [comment]
Minimal test for the original bug is:
```
from csympy import *
var("x y z")
e = (y+sqrt(3)*z)**2
g = e.expand()
```

**Comment by certik** [comment]
It fails because the Mul contains `{3^(1/2)*z: 1, y: 1}`, but it should contain `{1: 3^(1/2), z: 1, y: 1}` I guess, or something similar.

**Comment by certik** [comment]
@isuruf if you figure out how to fix this, let me know. I am going to bed now. Hopefully it's not something that slows things down.

**Comment by isuruf** [comment]
The issue is with this [line](https://github.com/sympy/csympy/blob/master/src/pow.cpp#L396). We are assuming that `tmp` is not a `Mul`

**Comment by certik** [comment]
I think you are right. So just an if statement should handle it.

**Comment by isuruf** [comment]
The second comment is a bug I had introduced in the last PR. Will send a fix. 
The original issue is a combination of two bugs. (The one I mentioned and `Mul::power_all_terms` not keeping the exponent as a fraction between 0 and 1)

**Comment by isuruf** [comment]
See #372
