### ISSUE TITLE
Expanding (sqrt(2)+sqrt(2)*x)**2 throws an error in `is_canonical`

### ISSUE THREAD

**Issue by isuruf** [sympy/csympy#397]
`((sqrt(2)+sqrt(2)*x)**2).expand()` gives `2 + 2*2*x + 2*x^2` when `CSYMPY_ASSERT` is off.

**Comment by certik** [comment]
Here is a full stacktrace:
```
In [3]: ((sqrt(2)+sqrt(2)*x)**2).expand()
python2.7: /home/ondrej/repos/csympy/src/mul.cpp:16: CSymPy::Mul::Mul(const CSymPy::RCP<const CSymPy::Number>&, CSymPy::map_basic_basic&&): Assertion `is_canonical(coef, dict_)' failed.

Abort caught. Printing stacktrace:

Traceback (most recent call last):
  File unknown, in _start()
  File "/build/buildd/eglibc-2.19/csu/libc-start.c", line 287, in __libc_start_main()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Modules/main.c", line 640, in Py_Main()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/pythonrun.c", line 955, in PyRun_SimpleFileExFlags()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/pythonrun.c", line 1377, in run_mod()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 673, in PyEval_EvalCode()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4346, in ext_do_call()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Objects/abstract.c", line 2529, in PyObject_Call()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Objects/funcobject.c", line 526, in function_call()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4129, in fast_function()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4730, in exec_statement()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 673, in PyEval_EvalCode()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 3265, in PyEval_EvalCodeEx()
  File "/home/ondrej/.hashdist/tmp/python-ctzx2dm36c6d/Python/ceval.c", line 4017, in call_function()
  File "/home/ondrej/repos/csympy/csympy/lib/csympy_wrapper.cpp", line 5803, in __pyx_pw_6csympy_3lib_14csympy_wrapper_5Basic_27expand()
    __pyx_r = __pyx_pf_6csympy_3lib_14csympy_wrapper_5Basic_26expand(((struct __pyx_obj_6csympy_3lib_14csympy_wrapper_Basic *)__pyx_v_self));
  File "/home/ondrej/repos/csympy/csympy/lib/csympy_wrapper.cpp", line 5839, in __pyx_pf_6csympy_3lib_14csympy_wrapper_5Basic_26expand()
    __pyx_t_1 = CSymPy::expand(((CSymPy::RCP<CSymPy::Basic const > &)__pyx_v_self->thisptr));
  File "/home/ondrej/repos/csympy/src/basic.cpp", line 41, in CSymPy::expand(CSymPy::RCP<CSymPy::Basic const> const&)
    if (is_a<Pow>(*self)) return pow_expand(rcp_static_cast<const Pow>(self));
  File "/home/ondrej/repos/csympy/src/pow.cpp", line 422, in CSymPy::pow_expand(CSymPy::RCP<CSymPy::Pow const> const&)
    RCP<const Basic> term = Mul::from_dict(overall_coeff, std::move(d));
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 214, in CSymPy::Mul::from_dict(CSymPy::RCP<CSymPy::Number const> const&, std::map<CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCPBasicKeyLess, std::allocator<std::pair<CSymPy::RCP<CSymPy::Basic const> const, CSymPy::RCP<CSymPy::Basic const> > > >&&)
    return rcp(new Mul(coef, std::move(d)));
  File "/home/ondrej/repos/csympy/src/mul.cpp", line 16, in CSymPy::Mul::Mul(CSymPy::RCP<CSymPy::Number const> const&, std::map<CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCP<CSymPy::Basic const>, CSymPy::RCPBasicKeyLess, std::allocator<std::pair<CSymPy::RCP<CSymPy::Basic const> const, CSymPy::RCP<CSymPy::Basic const> > > >&&)
    CSYMPY_ASSERT(is_canonical(coef, dict_))
  File "/build/buildd/eglibc-2.19/assert/assert.c", line 101, in __GI___assert_fail()
  File "/build/buildd/eglibc-2.19/assert/assert.c", line 92, in __assert_fail_base()
  File "/build/buildd/eglibc-2.19/stdlib/abort.c", line 89, in __GI_abort()
  File "/build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c", line 56, in __GI_raise()
  File unknown, in killpg()
  File "/home/ondrej/repos/csympy/src/teuchos/Teuchos_stacktrace.cpp", line 449, in loc_abort_callback_print_stack()
    Teuchos::show_stacktrace();

Done.
Aborted (core dumped)
```

**Comment by certik** [comment]
This fixes it:
```diff
diff --git a/src/pow.cpp b/src/pow.cpp
index 8b095f1..90ccfa6 100644
--- a/src/pow.cpp
+++ b/src/pow.cpp
@@ -398,7 +398,8 @@ RCP<const Basic> pow_expand(const RCP<const Pow> &self)
                     tmp = pow(base, exp);
                     if (is_a<Mul>(*tmp)) {
                         for (auto &p: (rcp_static_cast<const Mul>(tmp))->dict_) {
-                            Mul::dict_add_term(d, p.second, p.first);
+                            Mul::dict_add_term_new(outArg(overall_coeff), d,
+                                    p.second, p.first);
                         }
                         imulnum(outArg(overall_coeff), (rcp_static_cast<const Mul>(tmp))->coef_);
                     } else {
```
We just need to benchmark it, write a test, etc.
